In [1]:
# !pip install beautifulsoup4
# !pip install requests

In [2]:
import pandas as pd  
import requests      
from bs4 import BeautifulSoup 
import numpy as np 

In [3]:
url = 'https://www.isro.gov.in/Chandrayaan3_New.html'

In [4]:
response = requests.get(url)

In [5]:
soup = BeautifulSoup(response.content, 'html.parser')

In [6]:
whole_Text = soup.findAll('div', attrs= {'class': 'col-lg-9 col-md-9 col-sm-9 col-xl-9'})

In [7]:
texts = soup.find_all('p', class_ = 'pageContent')
para0 = texts[0]
para1 = texts[1]
para2 = texts[2]
para3 = texts[3]
para4 = texts[4]
text = para0.get_text(strip = True),para1.get_text(strip = True),para2.get_text(strip = True),para3.get_text(strip = True),para4.get_text(strip = True)

In [8]:
text

('Chandrayaan-3 is a follow-on mission to Chandrayaan-2 to demonstrate end-to-end capability in safe landing and roving on the lunar surface. It consists of Lander and Rover configuration. It will be launched by LVM3 from SDSC SHAR, Sriharikota. The propulsion module will carry the lander and rover configuration till 100 km lunar orbit. The propulsion module has Spectro-polarimetry of Habitable Planet Earth (SHAPE) payload to study the spectral and Polari metric measurements of Earth from the lunar orbit.',
 'Lander payloads:Chandra’s Surface Thermophysical Experiment (ChaSTE) to measure the thermal conductivity and temperature; Instrument for Lunar Seismic Activity (ILSA) for measuring the seismicity around the landing site; Langmuir Probe (LP) to estimate the plasma density and its variations. A passive Laser Retroreflector Array from NASA is accommodated for lunar laser ranging studies.',
 'Rover payloads:Alpha Particle X-ray Spectrometer (APXS) and Laser Induced Breakdown Spectrosc

In [9]:
Text = str(text)

In [10]:
type(Text)

str

In [11]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

In [12]:
with open("output_file.txt", 'r', encoding='utf-8') as myfile:
    mytext = myfile.read()

mytext

"('Chandrayaan-3 is a follow-on mission to Chandrayaan-2 to demonstrate end-to-end capability in safe landing and roving on the lunar surface. It consists of Lander and Rover configuration. It will be launched by LVM3 from SDSC SHAR, Sriharikota. The propulsion module will carry the lander and rover configuration till 100 km lunar orbit. The propulsion module has Spectro-polarimetry of Habitable Planet Earth (SHAPE) payload to study the spectral and Polari metric measurements of Earth from the lunar orbit.',\n 'Lander payloads:Chandra’s Surface Thermophysical Experiment (ChaSTE) to measure the thermal conductivity and temperature; Instrument for Lunar Seismic Activity (ILSA) for measuring the seismicity around the landing site; Langmuir Probe (LP) to estimate the plasma density and its variations. A passive Laser Retroreflector Array from NASA is accommodated for lunar laser ranging studies.',\n 'Rover payloads:Alpha Particle X-ray Spectrometer (APXS) and Laser Induced Breakdown Spectr

In [13]:
mytokenizer = Tokenizer()
mytokenizer.fit_on_texts([mytext])
total_words = len(mytokenizer.word_index) + 1

In [14]:
mytokenizer.word_index

{'the': 1,
 'and': 2,
 'of': 3,
 'to': 4,
 'lunar': 5,
 'module': 6,
 'lander': 7,
 'will': 8,
 'from': 9,
 'for': 10,
 'a': 11,
 'rover': 12,
 "'": 13,
 '3': 14,
 'is': 15,
 'in': 16,
 'surface': 17,
 'propulsion': 18,
 'carry': 19,
 'orbit': 20,
 'on': 21,
 'chandrayaan': 22,
 'landing': 23,
 'km': 24,
 'payloads': 25,
 'site': 26,
 'laser': 27,
 'an': 28,
 'lm': 29,
 'pm': 30,
 'which': 31,
 "'chandrayaan": 32,
 'mission': 33,
 'end': 34,
 'capability': 35,
 'it': 36,
 'consists': 37,
 'configuration': 38,
 'be': 39,
 'till': 40,
 '100': 41,
 'has': 42,
 'earth': 43,
 'payload': 44,
 'its': 45,
 'x': 46,
 'have': 47,
 'out': 48,
 'scientific': 49,
 'follow': 50,
 '2': 51,
 'demonstrate': 52,
 'safe': 53,
 'roving': 54,
 'launched': 55,
 'by': 56,
 'lvm3': 57,
 'sdsc': 58,
 'shar': 59,
 'sriharikota': 60,
 'spectro': 61,
 'polarimetry': 62,
 'habitable': 63,
 'planet': 64,
 'shape': 65,
 'study': 66,
 'spectral': 67,
 'polari': 68,
 'metric': 69,
 'measurements': 70,
 "'lander": 71,


In [15]:
my_input_sequences = []
for line in mytext.split('\n'):
    #print(line)
    token_list = mytokenizer.texts_to_sequences([line])[0]
    #print(token_list)
    for i in range(1, len(token_list)):
        my_n_gram_sequence = token_list[:i+1]
        print(my_n_gram_sequence)
        my_input_sequences.append(my_n_gram_sequence)

[32, 14]
[32, 14, 15]
[32, 14, 15, 11]
[32, 14, 15, 11, 50]
[32, 14, 15, 11, 50, 21]
[32, 14, 15, 11, 50, 21, 33]
[32, 14, 15, 11, 50, 21, 33, 4]
[32, 14, 15, 11, 50, 21, 33, 4, 22]
[32, 14, 15, 11, 50, 21, 33, 4, 22, 51]
[32, 14, 15, 11, 50, 21, 33, 4, 22, 51, 4]
[32, 14, 15, 11, 50, 21, 33, 4, 22, 51, 4, 52]
[32, 14, 15, 11, 50, 21, 33, 4, 22, 51, 4, 52, 34]
[32, 14, 15, 11, 50, 21, 33, 4, 22, 51, 4, 52, 34, 4]
[32, 14, 15, 11, 50, 21, 33, 4, 22, 51, 4, 52, 34, 4, 34]
[32, 14, 15, 11, 50, 21, 33, 4, 22, 51, 4, 52, 34, 4, 34, 35]
[32, 14, 15, 11, 50, 21, 33, 4, 22, 51, 4, 52, 34, 4, 34, 35, 16]
[32, 14, 15, 11, 50, 21, 33, 4, 22, 51, 4, 52, 34, 4, 34, 35, 16, 53]
[32, 14, 15, 11, 50, 21, 33, 4, 22, 51, 4, 52, 34, 4, 34, 35, 16, 53, 23]
[32, 14, 15, 11, 50, 21, 33, 4, 22, 51, 4, 52, 34, 4, 34, 35, 16, 53, 23, 2]
[32, 14, 15, 11, 50, 21, 33, 4, 22, 51, 4, 52, 34, 4, 34, 35, 16, 53, 23, 2, 54]
[32, 14, 15, 11, 50, 21, 33, 4, 22, 51, 4, 52, 34, 4, 34, 35, 16, 53, 23, 2, 54, 21]
[32, 14, 1

In [16]:
max_sequence_len = max([len(seq) for seq in my_input_sequences])
input_sequences = np.array(pad_sequences(my_input_sequences, maxlen=max_sequence_len, padding='pre'))

In [17]:
input_sequences[0]#0-194 total 195

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0, 32, 14])

In [18]:
input_sequences[327]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 169,  33, 170,
         3,  22,  14, 171,  13])

In [19]:
input_sequences[82] #For 1st paragragh upto\n

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0, 32, 14, 15, 11, 50, 21, 33,  4,
       22, 51,  4, 52, 34,  4, 34, 35, 16, 53, 23,  2, 54, 21,  1,  5, 17,
       36, 37,  3,  7,  2, 12, 38, 36,  8, 39, 55, 56, 57,  9, 58, 59, 60,
        1, 18,  6,  8, 19,  1,  7,  2, 12, 38, 40, 41, 24,  5, 20,  1, 18,
        6, 42, 61, 62,  3, 63, 64, 43, 65, 44,  4, 66,  1, 67,  2, 68, 69,
       70,  3, 43,  9,  1,  5, 20, 13])

In [20]:
X = input_sequences[:, :-1]
y = input_sequences[:, -1]

In [21]:
X

array([[  0,   0,   0, ...,   0,   0,  32],
       [  0,   0,   0, ...,   0,  32,  14],
       [  0,   0,   0, ...,  32,  14,  15],
       ...,
       [  0,   0,   0, ..., 170,   3,  22],
       [  0,   0,   0, ...,   3,  22,  14],
       [  0,   0,   0, ...,  22,  14, 171]])

In [23]:
y

array([ 14,  15,  11,  50,  21,  33,   4,  22,  51,   4,  52,  34,   4,
        34,  35,  16,  53,  23,   2,  54,  21,   1,   5,  17,  36,  37,
         3,   7,   2,  12,  38,  36,   8,  39,  55,  56,  57,   9,  58,
        59,  60,   1,  18,   6,   8,  19,   1,   7,   2,  12,  38,  40,
        41,  24,   5,  20,   1,  18,   6,  42,  61,  62,   3,  63,  64,
        43,  65,  44,   4,  66,   1,  67,   2,  68,  69,  70,   3,  43,
         9,   1,   5,  20,  13,  25,  72,  17,  73,  74,  75,   4,  76,
         1,  77,  78,   2,  79,  80,  10,   5,  81,  82,  83,  10,  84,
         1,  85,  86,   1,  23,  26,  87,  88,  89,   4,  90,   1,  91,
        92,   2,  45,  93,  11,  94,  27,  95,  96,   9,  97,  15,  98,
        10,   5,  27,  99, 100,  13,  25, 102, 103,  46, 104, 105, 106,
         2,  27, 107, 108, 109, 110,  10, 111,   1, 112, 113,  16,   1,
       114,   3,  23,  26,  13,  14,  37,   3,  28, 115,   7,   6,  29,
        18,   6,  30,   2,  11,  12, 116,  28, 117,   3, 118,   

In [24]:
y = np.array(tf.keras.utils.to_categorical(y, num_classes=total_words))

In [25]:
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [26]:
model = Sequential()
model.add(Embedding(total_words, 100, input_length=max_sequence_len-1))
model.add(LSTM(150))
model.add(Dense(total_words, activation='softmax'))
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 160, 100)          17200     
                                                                 
 lstm (LSTM)                 (None, 150)               150600    
                                                                 
 dense (Dense)               (None, 172)               25972     
                                                                 
Total params: 193,772
Trainable params: 193,772
Non-trainable params: 0
_________________________________________________________________
None


In [27]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X, y, epochs=100, verbose=1)

Epoch 1/100
11/11 [==============================] - 7s 229ms/step - loss: 5.1413 - accuracy: 0.0457
Epoch 2/100
11/11 [==============================] - 3s 249ms/step - loss: 4.9381 - accuracy: 0.0793
Epoch 3/100
11/11 [==============================] - 3s 263ms/step - loss: 4.8046 - accuracy: 0.0793
Epoch 4/100
11/11 [==============================] - 3s 255ms/step - loss: 4.7485 - accuracy: 0.0793
Epoch 5/100
11/11 [==============================] - 3s 265ms/step - loss: 4.7115 - accuracy: 0.0793
Epoch 6/100
11/11 [==============================] - 3s 264ms/step - loss: 4.6945 - accuracy: 0.0793
Epoch 7/100
11/11 [==============================] - 3s 262ms/step - loss: 4.6735 - accuracy: 0.0793
Epoch 8/100
11/11 [==============================] - 3s 264ms/step - loss: 4.6598 - accuracy: 0.0793
Epoch 9/100
11/11 [==============================] - 3s 259ms/step - loss: 4.6276 - accuracy: 0.0823
Epoch 10/100
11/11 [==============================] - 3s 249ms/step - loss: 4.5768 - accura

11/11 [==============================] - 4s 351ms/step - loss: 0.1603 - accuracy: 0.9939
Epoch 82/100
11/11 [==============================] - 4s 334ms/step - loss: 0.1559 - accuracy: 0.9939
Epoch 83/100
11/11 [==============================] - 4s 341ms/step - loss: 0.1511 - accuracy: 0.9970
Epoch 84/100
11/11 [==============================] - 4s 330ms/step - loss: 0.1470 - accuracy: 0.9970
Epoch 85/100
11/11 [==============================] - 4s 356ms/step - loss: 0.1415 - accuracy: 0.9939
Epoch 86/100
11/11 [==============================] - 3s 300ms/step - loss: 0.1367 - accuracy: 0.9970
Epoch 87/100
11/11 [==============================] - 3s 313ms/step - loss: 0.1318 - accuracy: 0.9939
Epoch 88/100
11/11 [==============================] - 4s 349ms/step - loss: 0.1292 - accuracy: 0.9970
Epoch 89/100
11/11 [==============================] - 4s 349ms/step - loss: 0.1253 - accuracy: 0.9970
Epoch 90/100
11/11 [==============================] - 4s 356ms/step - loss: 0.1229 - accuracy: 

In [28]:
input_text = "Chandrayan"
predict_next_words= 5

for _ in range(predict_next_words):
    token_list = mytokenizer.texts_to_sequences([input_text])[0]
    print(token_list)
    token_list = pad_sequences([token_list], maxlen=max_sequence_len-1, padding='pre')
    predicted = np.argmax(model.predict(token_list), axis=-1)
    output_word = ""
    for word, index in mytokenizer.word_index.items():
        if index == predicted:
            output_word = word
            break
    input_text += " " + output_word

print(input_text)

[]
1/1 [==============================] - 1s 546ms/step
[25]
1/1 [==============================] - 0s 23ms/step
[25, 102]
1/1 [==============================] - 0s 24ms/step
[25, 102, 103]
1/1 [==============================] - 0s 32ms/step
[25, 102, 103, 46]
1/1 [==============================] - 0s 56ms/step
Chandrayan payloads alpha particle x ray
